{% set name = "efficientnet-pytorch" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/efficientnet_pytorch-{{ version }}.tar.gz
  sha256: 00b9b261effce59d2d47aae2ad238c29a2a65175470f41ada7ecac439b7c1ee1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pytorch

test:
  imports:
    - efficientnet_pytorch

about:
  home: https://github.com/lukemelas/efficientnet_pytorch
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: EfficientNet implemented in PyTorch.
  dev_url: https://github.com/lukemelas/efficientnet_pytorch

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
